replicaCount: 1
image:
  repository: peishu/adservice
  tag: 01e73b58402b51376a9b46eaa665b8212cce7b95
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 9555
resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi
