replicaCount: 1
image:
  repository: peishu/adservice
  tag: b59d8dc8a0770143b7e9ebe088736d773583fd42
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 9555
resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi
